steps:
  # 単一コンテナでサーバープロセスの起動と疎通確認を行う
  - name: 'nginx:alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        nginx
        
        # プロセス確認
        ps aux | grep nginx
        
        # 少し待機
        sleep 3
        
        # 疎通確認（すでにnginxイメージにはcurlがインストールされていないので必要に応じてインストール）
        apk add --no-cache curl
        curl -s -v http://localhost
        
        # 成功したことを明示
        echo "疎通確認完了"

options:
  logging: CLOUD_LOGGING_ONLY